### ISSUE TITLE
Take screenshot

### ISSUE THREAD

**Issue by blenni** [TheRealLink/pylgtv#13]
Do you know if there's a possibility to take a screenshot of the image which is shown on the TV?

**Comment by Zibri** [comment]
Yes. It is.

**Comment by blenni** [comment]
Can you please tell me how to do it via python?

**Comment by Zibri** [comment]
when I will find a good working python program.. I will test and tell you.. but pylgtv seems not enough.. I will make some more tests...

**Comment by TheRealLink** [comment]
I would love to see your solution, since there is no official API for it and the luna service (luna://com.palm.systemmanager/takeScreenShot) was removed. Even the emulator uses vmbox's tools to take a screenshot.

Back in the netcast days you could do it by calling /roap/api/data?target=screen_image

**Comment by cyberluke** [comment]
@Zibri Do you have any other even non-Python way how to do it? I can port it to pylgtv. Already added Youtube support with opening custom link.

**Comment by Zibri** [comment]
sorry I can't disclose this information.

**Comment by cyberluke** [comment]
What does mean "disclose" in this context? Your answer was positive: "Yes. It is."

**Comment by Zibri** [comment]
It means that YES it's possible to take a screenshot, and no, I can't tell you how to do it.

**Comment by cyberluke** [comment]
So how do you know it's possible? Mainly regarding to previous comment that the service was removed from API: luna://com.palm.systemmanager/takeScreenShot

**Comment by cyberluke** [comment]
WTF is Luna? It is something different, not LG WebOS, right? https://stackoverflow.com/questions/6419662/grabbing-a-screenshot-programmatically-in-webos
http://webos-ports.org/wiki/Main_Page

But found this:
https://www.lgwebos.com/topic/1964-how-to-take-a-screenshot/

And this, but this is not WebOS, this is LG TV (old version):
https://github.com/StefanNemeth/PHP-LG-SmartTV


Anywayyyyyyyyyy thank you Zibri for not being a dick.....hahaha joke...you are actually huge dick!

**Comment by cyberluke** [comment]
Oh, they acquired (LG) the code from HP from mobile platform, now it makes sense: https://www.digitaltrends.com/home-theater/lg-webos-tv-platform-smart-tv/

**Comment by TheRealLink** [comment]
;) exactly, Palm -> HP -> LG

WebOS had quite a way to it’s current state

**Comment by cyberluke** [comment]
https://www.youtube.com/watch?v=xWguU43QRPQ

With MAGIC remote  under 4  color button , press : 
[ FOCUS ]  then look at TV screen , you can have a little windows for zoom, 
[RED ] button  =  Freez Screen
[GREEN] button = Save ScreenShot on internal memory,﻿

**Comment by cyberluke** [comment]
@TheRealLink Hi Dennis , please check my pull request. I need it for HomeAssistant pull request, so I can voice control, search & open Youtube videos straight away.

**Comment by TheRealLink** [comment]
I think we can close this issue
