### ISSUE TITLE
TV needs to be powered on at startup to work (with Home Assistant)

### ISSUE THREAD

**Issue by anthonymcmenzie** [TheRealLink/pylgtv#2]
I use Home Assistant and a component called WEBOSTV, which makes use of PYLGTV as a dependency.  It works really well, however then the initialisation happens, the TV needs to be powered on for the notify feature to work.  Is there any form of workaround that can be put in place for this?

Really appreciate the work !!

**Comment by andersonshatch** [comment]
I fixed this in home assistant so the TV doesn't have to be on when home assistant starts in order to register the notify component. It was fixed with this pull request https://github.com/home-assistant/home-assistant/pull/5967), which is now available in release 0.39.
