### ISSUE TITLE
Publish pylgtv on pypi

### ISSUE THREAD

**Issue by andrey-git** [TheRealLink/pylgtv#4]
Could you publish this package on Pypi, so it can be fetched without specifying the github URL?

home-assistant/home-assistant#7069

**Comment by andrey-git** [comment]
Also for pythinkingcleaner package :)

**Comment by TheRealLink** [comment]
Done =)

**Comment by tjorim** [comment]
@TheRealLink Could you push the newer versions (0.1.9) to Pypi as well please?
